server:
  port: 8082
  servlet:
    context-path: /spdev/erp
jwt:
  secret: cheweektttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttt
  validity: 300000
spring:
  profiles:
    active: ${CHW_SERVER_TYPE}
  datasource:
    url: ${CHW_PG_HOST}
    driverClassName: org.postgresql.Driver
    #spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
    username: ${CHW_PG_USER}
    password: ${CHW_PG_USPASS}
    hikari:
      maximum-pool-size: 20

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        dialect:
          storage_engine: innodb
    openInView: false
    show_sql: true
    generate-ddl: true
    hibernate.ddl-auto: update



custom:
  redis:
    host: dev2.sourcedagile.com
    port: 6379
    password: testM0r!al


chw:
  hashKeyToken: spring_dev_token
  companyList : spring_company_list
  branchList : spring_branch_list
  unitList : spring_unit_list
  propertiesList: spring_properties_list

service :
  erp:
    baseurl: ${SPRING_ERP_API}
    contextPath: ${SPRING_ERP_CONTEXT}
  core:
    baseurl: ${SPRING_CORE_API}
    contextPath: ${SPRING_CORE_CONTEXT}
  gateway:
    baseurl: ${SPRING_GATEWAY_API}
    contextPath: ${SPRING_GATEWAY_CONTEXT}









