
server:
  port: 8083
  servlet:
    context-path: /core
spring:
  profiles:
    active:  ${CHW_SERVER_TYPE}
  datasource:
        url: ${SPRING_CORE_URL}
        driverClassName: ${SPRING_CORE_DRIVER}
        username: ${SPRING_CORE_USERNAME}
        password: ${SPRING_CORE_PASSWORD}
        hikari:
            maximum-pool-size: ${SPRING_CORE_MAX_IDLE}
            minimum-idle: 1
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        dialect:
          storage_engine: innodb
    openInView: false
    show_sql: true
    generate-ddl: true
    hibernate.ddl-auto: update


custom:
  redis:
    host: ${CHW_REDIS_URL}
    port: ${CHW_REDIS_PORT}
    password: ${CHW_REDIS_AUTH}
#chw:
#  hashKeyToken: spring_dev_token
chw:
  hashKeyToken: spring_dev_token


service :
  erp:
    baseurl: ${SPRING_ERP_API}
    contextPath: ${SPRING_ERP_CONTEXT}
  core:
    baseurl: ${SPRING_CORE_API}
    contextPath: ${SPRING_CORE_CONTEXT}
  gateway:
    baseurl: ${SPRING_GATEWAY_API}
    contextPath: ${SPRING_GATEWAY_CONTEXT}




